# Generated by Django 5.2.17 on 2026-10-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='personalizados/')),
                ('detalle', models.TextField(blank=True, help_text='Ej: Talla M, en polera negra...')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
