# Generated by Django 5.2.5 on 2026-10-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_disenopersonalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenopersonalizado',
            name='nombre',
            field=models.TextField(blank=True, help_text='Ej: Oliver Contreras', null=True),
        ),
        migrations.AddField(
            model_name='disenopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
