# Generated by Django 5.2.5 on 2026-10-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_disenopersonalizado_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenopersonalizado',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
    ]
