# Generated by Django 5.2.5 on 2026-10-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_disenopersonalizado_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_total', models.IntegerField()),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada (Pagada)'), ('Rechazada', 'Rechazada / Cancelada')], default='Confirmada', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto', verbose_name='Polera')),
            ],
        ),
    ]
