# Generated by Django 5.2.5 on 2026-10-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría (Ej: Inglaterra)'),
        ),
    ]
