# Generated by Django 5.2.5 on 2026-10-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en el catálogo'),
        ),
    ]
