# Generated by Django 5.2.5 on 2026-10-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_extra/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='tienda.producto')),
            ],
        ),
    ]
